config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"
  get "show" => "static_pages#show"

  namespace :admin do
    get "/" => "system#dashboard"
    resources :products
    resource :system, only: [] do
      get "dashboard"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ProductImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    role == "admin"
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout "admin"
  before_action :authenticate_user!
  before_action :check_admin

  private
  def check_admin
    # redirect_to root_path unless current_user.admin?
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @q = Product.ransack params[:q]
    @products = @q.result.page params[:page]
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to [:admin, @product], notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to [:admin, @product], notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :root_price, :cur_price, :image)
    end
end

app/controllers/admin/system_controller.rb
class Admin::SystemController < Admin::BaseController

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/UI/_footer.html.haml
%footer#contact
  .container
    .row
      .col-md-4.col-sm-4
        %h2 Chung toi cam ket
        %hr
        %p Giao hang toan quoc
        %p Chung toi giao hang den 64 tinh thanh
        %hr
        %p Mien phi van chuyen noi thanh
        %p Chung toi hien dang mien phi van chuyen cho cac khang hang mua don hang tren 500 nghin VND trong cac quan noi thanh ha noi
        %hr
        %span hotline ho tro
        %strong 0123456789
      .col-md-4.col-sm-4
        %h2 Lien he
        %hr
        %p TRASEN.VN - Noi cung cap tra sen tay ho chinh hieu
        %p Tru so chinh: So 123 ABC, Quan XYZ, TP. Ha Noi
        %p Dia diem mua Tra Sen:
        %p Dia Diem 1: So 169 Nghi Tam, Q.Tay Ho, Tp. Ha Noi
        %p Dia Diem 2: So 133 Tran Cung, Q.Tay Ho, Tp. Ha Noi
        %hr
        %span Tong dai ho tro:
        %b 0123 456 789
        %br
        %span Hotline:
        %b 0123 456 789
        %br
        %span Email:
        %a{href: "#"} abc@gmail.com
      .col-md-4.col-sm-4.text-center.facebook
        .box-heading
          %h2 Chung toi tren Facebook
        %hr
        .box-content
          %span{:style => "vertical-align: bottom; width: 300px; height: 213px;"}
            %iframe{:allowfullscreen => "true", :allowtransparency => "true", :frameborder => "0", :height => "256px", :name => "f3a2cbc6dc", :scrolling => "no", :src => "https://www.facebook.com/v2.2/plugins/like_box.php?app_id=&channel=https%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter%2Fr%2F0eWevUAMuoH.js%3Fversion%3D42%23cb%3Df14038dca8%26domain%3Dlivedemo00.template-help.com%26origin%3Dhttps%253A%252F%252Flivedemo00.template-help.com%252Ff17197e1f8%26relation%3Dparent.parent&color_scheme=light&container_width=326&header=false&height=256&href=https%3A%2F%2Fwww.facebook.com%2FTemplateMonster&locale=en_US&sdk=joey&show_border=false&show_faces=true&stream=false&width=300", :style => "border: none; visibility: visible; width: 300px; height: 213px;", :title => "fb:like_box Facebook Social Plugin", :width => "300px"}

app/views/UI/_header.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"}
        %strong TRÀ SEN
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li
          %a{:href => "#slide"} HOME
        %li
          %a{:href => "#main_product"} SẢN PHẨM CHÍNH
        %li
          %a{:href => "#introduce_product"} TRANG TIN TỨC
      .col-md-3.col-sm-3
        %form.navbar-form{:role => "search"}
          .input-group
            %input.form-control{:name => "q", :placeholder => "Search", :type => "text"}/
            .input-group-btn
              %button.btn.btn-default{:type => "submit"}
                %i.glyphicon.glyphicon-search
      %ul.nav.navbar-nav.navbar-right
        %li
          %a{:href => "#contact"} LIÊN HỆ

app/views/admin/products/_form.html.erb
<%= form_for [:admin, product] do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :root_price %>
    <%= f.number_field :root_price %>
  </div>

  <div class="field">
    <%= f.label :cur_price %>
    <%= f.number_field :cur_price %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', [:admin, @product] %> |
<%= link_to 'Back', admin_products_path %>

app/views/admin/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<%= search_form_for [:admin, @q], url: admin_products_path do |f| %>
  <%= f.label :description_cont %>
  <%= f.search_field :description_cont %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Root price</th>
      <th>Cur price</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.root_price %></td>
        <td><%= product.cur_price %></td>
        <td><%= image_tag product.image %></td>
        <td><%= link_to 'Show', [:admin, product] %></td>
        <td><%= link_to 'Edit', edit_admin_product_path(product) %></td>
        <td><%= link_to 'Destroy', [:admin, product], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @products %>
<br>

<%= link_to 'New Product', new_admin_product_path %>

app/views/admin/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', admin_products_path %>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Root price:</strong>
  <%= @product.root_price %>
</p>

<p>
  <strong>Cur price:</strong>
  <%= @product.cur_price %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @product.image %>
</p>

<%= link_to 'Edit', edit_admin_product_path(@product) %> |
<%= link_to 'Back', admin_products_path %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trasen</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "Log out", destroy_user_session_path(), method: :delete %>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trasen</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-spy="scroll" data-target=".navbar" data-offset="50">
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.haml
= render "UI/header"
.section#slide
  %br
  #myCarousel.carousel.slide{"data-ride" => "carousel"}
    / Indicators
    %ol.carousel-indicators
      %li.active{"data-slide-to" => "0", "data-target" => "#myCarousel"}
      %li{"data-slide-to" => "1", "data-target" => "#myCarousel"}
      %li{"data-slide-to" => "2", "data-target" => "#myCarousel"}
      %li{"data-slide-to" => "3", "data-target" => "#myCarousel"}
    / Wrapper for slides
    .carousel-inner{:role => "listbox"}
      .item.active
        %img{:alt => "Chania", :height => "345", :src => "assets/slide/img-1.jpg", :width => "100%"}
        .carousel-caption
          %h3 Chania
          %p The atmosphere in Chania has a touch of Florence and Venice.
      .item
        %img{:alt => "Chania", :height => "345", :src => "assets/slide/img-2.jpg", :width => "100%"}
        .carousel-caption
          %h3 Chania
          %p The atmosphere in Chania has a touch of Florence and Venice.
      .item
        %img{:alt => "Flower", :height => "345", :src => "assets/slide/img-3.jpg", :width => "100%"}
        .carousel-caption
          %h3 Chania
          %p The atmosphere in Chania has a touch of Florence and Venice.
      .item
        %img{:alt => "Flower", :height => "345", :src => "assets/slide/img-4.jpg", :width => "100%"}
        .carousel-caption
          %h3 Chania
          %p The atmosphere in Chania has a touch of Florence and Venice.
    / Left and right controls
    %a.left.carousel-control{"data-slide" => "prev", :href => "#myCarousel", :role => "button"}
      %span.glyphicon.glyphicon-chevron-left{"aria-hidden" => "true"}
      %span.sr-only Previous
    %a.right.carousel-control{"data-slide" => "next", :href => "#myCarousel", :role => "button"}
      %span.glyphicon.glyphicon-chevron-right{"aria-hidden" => "true"}
      %span.sr-only Next
%div{style: "width:  100%;"}
.section#main_product{style: "padding-top: 50px"}
  .container
    .row
      %h1.text-center{style: "font-size: 50px; margin-bottom: 40px;"} Những sản phẩm nổi bật
      - 4.times do |n|
        %a.product{href: "/show"}
          .col-md-3.col-sm-6.product-wrap
            .col-md-12.rating-show
              %i.fa.fa-star
              %i.fa.fa-star
              %i.fa.fa-star
              %i.fa.fa-star
              %i.fa.fa-star-half-o
            .col-md-12.text-center{style: "padding: 20px"}
              %img.img-rounded{src: "assets/products/img-#{n + 1}.jpg", style: "width: 100%; height: 190px"}
            .col-md-12
              .price.text-center
                %span
                  %b $400
                %small{style: "text-decoration: line-through;"} $500
              .title.text-center
                %h3 Trà sen ướp tuyết
              .content
                %p{style: "text-align: justify"} Được mệnh danh là “Thiên cổ đệ nhất trà”, là loại trà tinh tế nhất của Việt Nam, các nước khác trên thế giới không có được. Nguyên liệu trà được dùng là những búp trà cổ thụ mọc trên núi cao, mỗi năm chỉ hái được 4 lần vào 4 mùa xuân, hạ, thu, đông.
            .col-md-12.btn-active
              %span.btn-btn-default.btn-rating
                %i.fa.fa-star
.jumbotron#introduce_product
  .container
    .row{style: "height: 110px; margin-bottom: 50px;"}
      .col-md-12
        %h1 TRÀ SEN TÂY HỒ
        %ul
          %li
            %a{href: "%"} Trà sen
          %li
            %a{href: "%"} Trà việt nam
          %li
            %a{href: "%"} Trà thư
          %li
            %a{href: "%"} Trà cụ khác
        %span.line-home{src: "assets/backline.png", style: "width: 100%; height: 17px; position: absolute;"}
    .row.suggest
      - 5.times do |n|
        %a.article{href: "#"}
          .col-md-4.col-sm-6{style: "margin-bottom: 25px"}
            %img{src: "assets/square/img-#{n+1}.jpg", style: "width: 100%;"}
            %a{href: "#"}
              %span.title Trà sen trong ký ức
= render "UI/footer"

= stylesheet_link_tag "home"
= javascript_include_tag "home"

app/views/static_pages/show.html.haml
= render "UI/header"
.section#product-section{style: ""}
  .container
    %ol.breadcrumb
      %li.breadcrumb-item
        %a{:href => "#"} Home
      %li.breadcrumb-item
        %a{:href => "#"} Library
      %li.breadcrumb-item.active
        %span Data
    .row.product-basic-information
      .col-md-12
        .col-lg-7.left-wrap
          .image-thumb
            %ul
              - 5.times do |n|
                %li
                  %img{src: "assets/square/img-#{n+1}.jpg"}
          .product-image
            %img{src: "assets/square/img-1.jpg"}
        .col-lg-5.right-wrap
          %h1.product-name
            %b Quisque eget
          .rating-section
            .rating
              %i.fa.fa-star
              %i.fa.fa-star
              %i.fa.fa-star
              %i.fa.fa-star
              %i.fa.fa-star-half-o
              %a{href: "#reviews-section"} 3 reviews
              \/
              %a{href: "#form-reivew-section"} Write a review
          .price-section
            %span
              %b $400
            %small{style: "text-decoration: line-through;"} $500
          %hr
          %h3.properties-title
            %b Properties
          %ul.product-properties
            %li
              Brand:
              %span Lorem ipsum
            %li
              Product Code:
              %span Product 16
            %li
              Reward Points:
              %span 600
            %li
              Availability:
              %span In Stock
.section#desciption-section
  .container
    .row
      %h1.text-center.description-title
        %b Description
      .description-video.pull-left
        %iframe{:allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/8mvK9WZj1ko?rel=0&controls=0&showinfo=0", :width => "560"}
      .description-content
        %span Would you like a cup of tea? We have a wide range of fresh teas and the products to serve them! Our gourmet tea assortments will suit any occasion and any taste. Green tea, black tea, white tea, flavored tea and many others to surprise and astonish you! We are experts in tea and we will teach you this art with pleasure! If you are already a tea lover, you will find a real paradise of tea aromas and tastes visiting our Tea store.

        Our goal is to fill your cup with joy you can share with guests and friends leaving far away boring fuss. Turn your tea time into a special ceremony we have cared about proposing you the products of premium quality only. This old drink with a long history and deserved love of millions is worth of a proper attitude and we are glad to share with you a nice collection of teapots, mugs, cups, kettles, tea sets and other useful accessories which will add your tea time with necessary charm and luxury. We have tea blends for any situation and mood: taste our teas to wake up, relax, rejuvenate. Do you want some exotic tea? You are welcome. We are ready to please tea beginners and tea gurus.

.section#reviews-section
  .container
    %h1.text-center.reviews-title
      %b Reviews(3)
    .reviews-content
      - 3.times do
        .row
          .col-md-3.reviews-left.text-center
            .review-score
              %i.fa.fa-star
              %i.fa.fa-star
              %i.fa.fa-star
              %i.fa.fa-star
              %i.fa.fa-star-half-o
            .review-author
              %span Le Dinh Minh
            .review-date
              %span 17/09/1991
          .col-md-9.reviews-right
            %p Vestibulum ut neque eget dui tincidunt molestie. Mauris accumsan fermentum mi a cursus. Aenean ac mauris eget mi consectetur tristique vitae in nisi. In posuere lorem non eleifend suscipit. Vestibulum non nunc eu mauris lacinia malesuada nec vitae velit. Vivamus tincidunt aliquam elementum. Aliquam ut faucibus lacus.
        %hr

.section#form-reivew-section
  .container
    %h1.text-center.reviews-title
      %b Write a review
    .form-write-review
      .row
        %form.form-horizontal
          .form-group
            %label.control-label.col-md-3 Your Name
            .col-md-9
              %input.form-control
          .form-group
            %label.control-label.col-md-3 Your Review
            .col-md-9
              %textarea.form-control
          .form-group
            %label.control-label.col-md-3 Rating
            .col-md-9
              %label.radio-inline
                %input{:name => "optradio", :type => "radio"}>
                Very Bad
              %label.radio-inline
                %input{:name => "optradio", :type => "radio"}>
                Bad
              %label.radio-inline
                %input{:name => "optradio", :type => "radio"}>
                Normal
              %label.radio-inline
                %input{:name => "optradio", :type => "radio"}>
                Good
              %label.radio-inline
                %input{:name => "optradio", :type => "radio"}>
                Very Good
          .form-group
            %label.control-label.col-md-3 Enter the code in the box below
            .col-md-9
              %input.form-control
          .form-group
            .col-md-9.col-md-offset-3
              %img#captcha{src: "#"}
              %span.btn.btn-primary.btn-review.pull-right Continue


= render "UI/footer"
= stylesheet_link_tag "show"

:javascript
  //click change image product #product-section
  $(".image-thumb img").click(function(){
    $(".product-image:visible img").attr("src", $(this).attr("src"));
  })